// File generated by FlutterFire CLI.
// This file is used to configure Firebase for your Flutter app.
// Replace this with your actual Firebase configuration file.

import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  // Web configuration for the new Chhar project
  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDF0ACOo8QZ5a7j3v2pcCfJMjQLGeOEAeQ',
    appId: '1:116492105724:web:57bee91a8c063c85cba30c',
    messagingSenderId: '116492105724',
    projectId: 'chhar-app',
    authDomain: 'chhar-app.firebaseapp.com',
    storageBucket: 'chhar-app.appspot.com',
  );

  // Android configuration for the new Chhar project
  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDF0ACOo8QZ5a7j3v2pcCfJMjQLGeOEAeQ',
    appId: '1:116492105724:android:bad2fc800fa00256d6479',
    messagingSenderId: '116492105724',
    projectId: 'chhar-app',
    storageBucket: 'chhar-app.appspot.com',
  );

  // iOS configuration for the new Chhar project
  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDF0ACOo8QZ5a7j3v2pcCfJMjQLGeOEAeQ',
    appId: '1:116492105724:ios:5e7e3a92c88b5ce5cba30c',
    messagingSenderId: '116492105724',
    projectId: 'chhar-app',
    storageBucket: 'chhar-app.appspot.com',
    iosClientId: '116492105724-ios-client-id', // You'll need to update this with actual iOS client ID
    iosBundleId: 'com.example.chhar',
  );

  // macOS configuration for the new Chhar project
  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDF0ACOo8QZ5a7j3v2pcCfJMjQLGeOEAeQ',
    appId: '1:116492105724:ios:5e7e3a92c88b5ce5cba30c',
    messagingSenderId: '116492105724',
    projectId: 'chhar-app',
    storageBucket: 'chhar-app.appspot.com',
    iosClientId: '116492105724-ios-client-id', // You'll need to update this with actual iOS client ID
    iosBundleId: 'com.example.chhar',
  );
} 